"""Add assigned_zone_id and InterventionAudit

Revision ID: 6bc909c509d6
Revises: 1514855f8762
Create Date: 2026-08-17 18:00:49.416074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6bc909c509d6'
down_revision: Union[str, Sequence[str], None] = '1514855f8762'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('intervention_audits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('intervention_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=False),
    sa.Column('previous_status', sa.Enum('PROPOSED', 'SIMULATING', 'PENDING_APPROVAL', 'APPROVED', 'REJECTED', 'ACTIVATED', 'COMPLETED', 'CANCELLED', name='interventionstatus'), nullable=True),
    sa.Column('new_status', sa.Enum('PROPOSED', 'SIMULATING', 'PENDING_APPROVAL', 'APPROVED', 'REJECTED', 'ACTIVATED', 'COMPLETED', 'CANCELLED', name='interventionstatus'), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['intervention_id'], ['interventions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('intervention_audits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_intervention_audits_actor_user_id'), ['actor_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_intervention_audits_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_intervention_audits_intervention_id'), ['intervention_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_zone_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_users_assigned_zone_id_zones', 'zones', ['assigned_zone_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('fk_users_assigned_zone_id_zones', type_='foreignkey')
        batch_op.drop_column('assigned_zone_id')

    with op.batch_alter_table('intervention_audits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_intervention_audits_intervention_id'))
        batch_op.drop_index(batch_op.f('ix_intervention_audits_id'))
        batch_op.drop_index(batch_op.f('ix_intervention_audits_actor_user_id'))

    op.drop_table('intervention_audits')
    # ### end Alembic commands ###
