"""Add status to zone_connections

Revision ID: 9dae08c950db
Revises: 6bc909c509d6
Create Date: 2026-08-17 18:57:10.262917

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9dae08c950db'
down_revision: Union[str, Sequence[str], None] = '6bc909c509d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('zone_connections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Enum('OPEN', 'CLOSED', 'RESTRICTED', name='connectionstatus'), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('zone_connections', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
