"""Add AuditLog model

Revision ID: b05c137922f0
Revises: 1514855f8762
Create Date: 2026-08-17 19:00:17.874385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b05c137922f0'
down_revision: Union[str, Sequence[str], None] = '1514855f8762'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('actor_role', sa.String(length=50), nullable=True),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('zone_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('previous_state', sa.String(length=100), nullable=True),
    sa.Column('new_state', sa.String(length=100), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_actor_user_id'), ['actor_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_entity_type'), ['entity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_zone_id'), ['zone_id'], unique=False)
        
    # op.drop_table('intervention_audit_logs')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_event_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('assigned_zone_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_assigned_event_id'), ['assigned_event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_assigned_zone_id'), ['assigned_zone_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('intervention_audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('intervention_id', sa.Integer(), nullable=False),
    sa.Column('changed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('previous_status', sa.VARCHAR(length=16), nullable=True),
    sa.Column('new_status', sa.VARCHAR(length=16), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['intervention_id'], ['interventions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_intervention_audit_logs_intervention_id', 'intervention_audit_logs', ['intervention_id'], unique=False)
    op.create_index('ix_intervention_audit_logs_id', 'intervention_audit_logs', ['id'], unique=False)
    op.create_index('ix_intervention_audit_logs_changed_by_user_id', 'intervention_audit_logs', ['changed_by_user_id'], unique=False)
    
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_assigned_zone_id'))
        batch_op.drop_index(batch_op.f('ix_users_assigned_event_id'))
        batch_op.drop_column('assigned_zone_id')
        batch_op.drop_column('assigned_event_id')

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_zone_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_event_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_entity_type'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_entity_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_actor_user_id'))

    op.drop_table('audit_logs')
    # ### end Alembic commands ###
