"""Add target_role to alerts

Revision ID: b132c14fa1b7
Revises: b05c137922f0
Create Date: 2026-08-19 17:59:36.833329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b132c14fa1b7'
down_revision: Union[str, Sequence[str], None] = 'b05c137922f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_reads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alert_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alert_id', 'user_id', name='uq_alert_user_read')
    )
    with op.batch_alter_table('alert_reads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alert_reads_alert_id'), ['alert_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alert_reads_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alert_reads_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('target_role', sa.Enum('CITIZEN', 'AUTHORITY', 'ADMIN', name='userrole'), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_column('target_role')

    with op.batch_alter_table('alert_reads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alert_reads_user_id'))
        batch_op.drop_index(batch_op.f('ix_alert_reads_id'))
        batch_op.drop_index(batch_op.f('ix_alert_reads_alert_id'))

    op.drop_table('alert_reads')
    # ### end Alembic commands ###
