"""Add routing graph

Revision ID: cad53d8479ca
Revises: 3d6ea6ed83f4
Create Date: 2026-08-16 11:21:29.979194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cad53d8479ca'
down_revision: Union[str, Sequence[str], None] = '3d6ea6ed83f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zone_connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_zone_id', sa.Integer(), nullable=False),
    sa.Column('dest_zone_id', sa.Integer(), nullable=False),
    sa.Column('distance', sa.Float(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('is_bidirectional', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['dest_zone_id'], ['zones.id'], ),
    sa.ForeignKeyConstraint(['source_zone_id'], ['zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zone_connections_dest_zone_id'), 'zone_connections', ['dest_zone_id'], unique=False)
    op.create_index(op.f('ix_zone_connections_id'), 'zone_connections', ['id'], unique=False)
    op.create_index(op.f('ix_zone_connections_source_zone_id'), 'zone_connections', ['source_zone_id'], unique=False)
    op.add_column('zones', sa.Column('is_exit', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('zones', 'is_exit')
    op.drop_index(op.f('ix_zone_connections_source_zone_id'), table_name='zone_connections')
    op.drop_index(op.f('ix_zone_connections_id'), table_name='zone_connections')
    op.drop_index(op.f('ix_zone_connections_dest_zone_id'), table_name='zone_connections')
    op.drop_table('zone_connections')
    # ### end Alembic commands ###
